name: Deploy Images to GHCR

#env:

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
      push-store-image:
        runs-on: ubuntu-latest
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v2
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - name: 'Build Container'
            run: |
              docker build . --tag ghcr.io/iandday/nfdump-csv:latest
              docker push ghcr.io/iandday/nfdump-csv:latest
